import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseAgentsMarkdown, readAgentsMd } from "./agents-md.js";
import type { TeamConfig } from "./types.js";
import { canonicalizeAgentId } from "./ids.js";

export interface WorkerPersona {
  title: string;
  focus: string;
}

export interface ProjectProfile {
  domain: string;
  summary: string;
  /** Worker id (B, C, …) → specialist persona for this repo */
  workers: Record<string, WorkerPersona>;
  sources: string[];
  adaptedAt: string | null;
  /** Lead-only: respect existing user/project prompts */
  layeringNote?: string;
}

export const DEFAULT_LAYERING_NOTE =
  "Project rules (.cursor/rules), AGENTS.md, and the user's existing system prompts define domain expertise. Agent-team rules add multi-window coordination only — do not replace or contradict project instructions.";

export const PROJECT_PROFILE_PATH = "team/project.json";
export const PROJECT_MARKDOWN_PATH = "knowledge/project.md";

export const PROJECT_MARKDOWN_TEMPLATE = `# Project team profile

Edit this file (or run \`/team-adapt\` in the lead chat) when the repo changes focus.

## Domain

(What this codebase is — e.g. PS3 reverse engineering, DayZ modding, web API.)

## Summary

(2–4 sentences the whole team should share.)

## Specialists

Map each worker id from \`team/config.json\` to a role **for this repo**. Workers read their section on every order.

### B

- **Title:** (e.g. Lead gameplay scripter)
- **Focus:** (what B owns in this project)

### C

- **Title:**
- **Focus:**

### D

- **Title:**
- **Focus:**

## Sources

(List files the lead used: README, AGENTS.md, rules, etc.)

## Layering

${DEFAULT_LAYERING_NOTE}
`;

export function isPluginDevWorkspace(workspaceRoot: string): boolean {
  try {
    const pkg = JSON.parse(
      readFileSync(path.join(workspaceRoot, "package.json"), "utf8"),
    ) as { name?: string };
    return pkg.name === "cursor-agent-team";
  } catch {
    return false;
  }
}

export function projectJsonPath(workspaceRoot: string): string {
  return path.join(workspaceRoot, PROJECT_PROFILE_PATH);
}

export function readProjectProfile(workspaceRoot: string): ProjectProfile | null {
  const file = projectJsonPath(workspaceRoot);
  if (!existsSync(file)) return null;
  try {
    const raw = JSON.parse(readFileSync(file, "utf8")) as Partial<ProjectProfile>;
    if (!raw.domain && !raw.summary && !raw.workers) return null;
    return {
      domain: String(raw.domain ?? ""),
      summary: String(raw.summary ?? ""),
      workers: raw.workers ?? {},
      sources: Array.isArray(raw.sources) ? raw.sources.map(String) : [],
      adaptedAt: raw.adaptedAt ?? null,
      layeringNote: raw.layeringNote ?? DEFAULT_LAYERING_NOTE,
    };
  } catch {
    return null;
  }
}

export function personaForWorker(
  profile: ProjectProfile | null,
  workerId: string,
): WorkerPersona | null {
  if (!profile?.workers) return null;
  const id = canonicalizeAgentId(workerId);
  return profile.workers[id] ?? profile.workers[id.toLowerCase()] ?? null;
}

export function enrichDelegateBrief(
  profile: ProjectProfile | null,
  to: string,
  brief: string,
): string {
  if (!profile) return brief;
  const parts: string[] = [brief.trim()];
  const head = [profile.domain, profile.summary].filter(Boolean).join(" — ");
  if (head) {
    parts.push("", "## Project context", head);
  }
  const persona = personaForWorker(profile, to);
  if (persona) {
    parts.push(
      "",
      `## Your role (worker ${canonicalizeAgentId(to)})`,
      `**${persona.title}** — ${persona.focus}`,
    );
  }
  return parts.join("\n");
}

export function defaultWorkersFromConfig(config: TeamConfig): Record<string, WorkerPersona> {
  const out: Record<string, WorkerPersona> = {};
  for (const w of config.workers) {
    const id = canonicalizeAgentId(w);
    out[id] = {
      title: `Specialist ${id}`,
      focus: "Execute lead orders using this repo's rules and docs.",
    };
  }
  return out;
}

export function projectMarkdownExists(workspaceRoot: string): boolean {
  return existsSync(path.join(workspaceRoot, PROJECT_MARKDOWN_PATH));
}

export function renderProjectMarkdown(profile: ProjectProfile): string {
  const lines = [
    "# Project team profile",
    "",
    "Generated by `/team-adapt` or `team_adapt`. Chat overrides beat AGENTS.md when both exist.",
    "",
    "## Domain",
    "",
    profile.domain || "(not set)",
    "",
    "## Summary",
    "",
    profile.summary || "(not set)",
    "",
    "## Specialists",
    "",
  ];
  const ids = Object.keys(profile.workers).sort((a, b) => personaSortKey(a).localeCompare(personaSortKey(b)));
  for (const id of ids) {
    const persona = profile.workers[id]!;
    lines.push(`### ${id}`, "", `- **Title:** ${persona.title}`, `- **Focus:** ${persona.focus}`, "");
  }
  lines.push(
    "## Sources",
    "",
    profile.sources.length ? profile.sources.map((s) => `- ${s}`).join("\n") : "(none)",
    "",
    "## Layering",
    "",
    profile.layeringNote ?? DEFAULT_LAYERING_NOTE,
    "",
  );
  return lines.join("\n");
}

function personaSortKey(id: string): string {
  if (/^[A-Z]$/.test(id)) return `0${id}`;
  if (/^\d+$/.test(id)) return `1${id.padStart(6, "0")}`;
  return `2${id}`;
}

const GENERIC_FOCUS = "Execute lead orders using this repo's rules and docs.";

/**
 * Add a persona for a worker who just joined, without dropping anyone already in the profile.
 * AGENTS.md wins when it has a section for that id; otherwise a generic specialist is used.
 */
export function ensureWorkerPersona(workspaceRoot: string, workerId: string): WorkerPersona {
  const id = canonicalizeAgentId(workerId);
  const existing = readProjectProfile(workspaceRoot);
  const already = personaForWorker(existing, id);
  if (existing && already) return already;

  const agents = readAgentsMd(workspaceRoot);
  let persona: WorkerPersona = { title: `Specialist ${id}`, focus: GENERIC_FOCUS };
  const sources = new Set(existing?.sources ?? []);
  let domain = existing?.domain ?? "";
  let summary = existing?.summary ?? "";
  if (agents) {
    const parsed = parseAgentsMarkdown(agents, [id]);
    if (parsed.workers[id]) persona = parsed.workers[id];
    if (!domain && parsed.domain) domain = parsed.domain;
    if (!summary && parsed.summary) summary = parsed.summary;
    sources.add("AGENTS.md");
  }

  const profile: ProjectProfile = {
    domain,
    summary,
    workers: { ...(existing?.workers ?? {}), [id]: persona },
    sources: [...sources],
    adaptedAt: new Date().toISOString(),
    layeringNote: existing?.layeringNote ?? DEFAULT_LAYERING_NOTE,
  };
  writeFileSync(projectJsonPath(workspaceRoot), `${JSON.stringify(profile, null, 2)}\n`, "utf8");
  writeFileSync(
    path.join(workspaceRoot, PROJECT_MARKDOWN_PATH),
    renderProjectMarkdown(profile),
    "utf8",
  );
  return persona;
}
